[tool.poetry]
name = "electricity-consumption"
version = "0.1.0"
description = ""
authors = ["Tero Paloheimo <tero.paloheimo@iki.fi>"]
readme = "README.md"
packages = [{include = "electricity_consumption"}]

[tool.poetry.dependencies]
python = "^3.12"
psycopg = {extras = ["binary"], version = "^3.1.8"}
pycaruna = "^1.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
lint.select = ["B", "D", "E", "F", "G", "I", "N", "PERF", "PIE", "PL", "PTH", "SIM", "RUF", "S", "TRY", "W"]
lint.ignore = ["D203", "D213"]
target-version = "py312"
