language: clojure
jdk:
  - openjdk8
  - openjdk11
env:
  global:
  - POSTGRESQL_DB_HOST=localhost
  - POSTGRESQL_DB_PORT=5433
  - POSTGRESQL_DB_USERNAME=postgres
  - POSTGRESQL_DB_PASSWORD=
  - PGPORT=5433
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
before_install:
  # Hack needed to have working authententication with the postgres user
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/12/main/pg_hba.conf
  - sudo systemctl restart postgresql@12-main.service
before_script:
  - psql -U postgres -c 'CREATE DATABASE env_logger_test;'
  - psql -U postgres env_logger_test < db-def.sql
  - cp resources/config.edn_sample resources/config.edn
script:
  - lein test
