# Check https://circleci.com/docs/2.0/language-clojure/ for more details
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/clojure:1.10
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/env_logger_test
      - image: cimg/postgres:13.5
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: env_logger_test
          POSTGRES_PASSWORD: testpwd

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
      POSTGRESQL_DB_USERNAME: postgres
      POSTGRESQL_DB_PASSWORD: testpwd

    steps:
      - checkout

      - run:
          name: database setup
          command: |
            sudo apt install -y postgresql-client || true
            psql -d ${TEST_DATABASE_URL} env_logger_test < db-def.sql

      - run:
          name: setup config
          command: |
            cp resources/config.edn_sample resources/config.edn

      - run: clojure -T:build ci
