FROM ghcr.io/astral-sh/uv:python3.14-trixie-slim AS builder
ENV UV_COMPILE_BYTECODE=1
WORKDIR /app
RUN --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-dev

LABEL org.opencontainers.image.authors="tero.paloheimo@iki.fi"

FROM python:3.14-slim
ENV PYTHONUNBUFFERED=true

RUN apt-get update && apt-get upgrade -y && apt-get clean

# Add user to run the app
ARG APPLICATION_USER=appuser
RUN useradd --no-create-home -u 1000 ${APPLICATION_USER}

WORKDIR /usr/src/app

# Copy the application from the builder
COPY --from=builder --chown=${APPLICATION_USER}:${APPLICATION_USER} \
     /app .

COPY --chown=${APPLICATION_USER}:${APPLICATION_USER} \
     monitor.cfg monitor.py .

# Place executables in the environment at the front of the path
ENV PATH="/usr/src/app/.venv/bin:${PATH}"

# Set IPv4 preference over IPv6 so that broken IPv6 environments cause minimal
# delay for network operations
RUN sed -i 's|#precedence ::ffff:0:0/96  100|precedence ::ffff:0:0/96  100|' /etc/gai.conf

USER ${APPLICATION_USER}
ENTRYPOINT ["python", "monitor.py"]
