FROM ghcr.io/astral-sh/uv:python3.14-alpine AS builder
ENV UV_COMPILE_BYTECODE=1
WORKDIR /app

RUN --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-dev --no-cache

FROM docker.io/python:3.14-alpine
LABEL org.opencontainers.image.authors="tero.paloheimo@iki.fi"
ENV PYTHONUNBUFFERED=true

ARG APPLICATION_USER=appuser
# Add user to run the app
RUN adduser --no-create-home -u 1000 -D ${APPLICATION_USER}

WORKDIR /usr/src/app

# Copy the virtual environment from the builder
COPY --from=builder --chown=${APPLICATION_USER}:${APPLICATION_USER} \
     /app/.venv ./.venv

COPY --chown=${APPLICATION_USER}:${APPLICATION_USER} \
     monitor.cfg monitor.py .

# Place executables in the environment at the front of the path
ENV PATH="/usr/src/app/.venv/bin:${PATH}"

USER ${APPLICATION_USER}
ENTRYPOINT ["python", "monitor.py"]
