[tool.poetry]
name = "obs-monitor"
version = "0.1.0"
description = "env-logger observation monitor"
authors = ["Tero Paloheimo <tero.paloheimo@iki.fi>"]
packages = [{include = "monitor.py"}]

[tool.poetry.dependencies]
python = "^3.10"
psycopg = {extras = ["binary"], version = "^3.1.8"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
