target-version = "py314"
lint.select = ["A", "ASYNC", "B", "BLE", "C4", "C90", "D", "DTZ", "E", "EM", "ERA", "F", "FURB", "G", "I", "ISC", "LOG", "N", "PERF", "PIE", "PGH", "PL", "PTH", "RET", "RSE", "RUF", "S", "SIM", "T10", "TRY", "UP", "W"]
lint.ignore = ["D203", "D213"]
