[tool.poetry]
name = "logger"
version = "0.1.0"
description = "An environment logger script"
authors = ["Tero Paloheimo <tero.paloheimo@iki.fi>"]
readme = "README.md"
packages = [{include = "logger.py"}]

[tool.poetry.dependencies]
python = "^3.12"
pyserial = "^3.5"
pytz = "^2024.0"
requests = "^2.30.0"
ruuvitag-sensor = { git = "https://github.com/ttu/ruuvitag-sensor.git" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
lint.select = ["B", "D", "E", "F", "G", "I", "N", "PERF", "PIE", "PL", "PTH", "SIM", "RUF", "S", "TRY", "W"]
lint.ignore = ["D203", "D213"]
target-version = "py312"
