[tool.poetry]
name = "testbed-image"
version = "0.1.0"
description = "FMI Testbed image fetcher"
authors = ["Tero Paloheimo <tero.paloheimo@iki.fi>"]
packages = [{include = "testbed_image.py"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"
beautifulsoup4 = "^4.11.2"
pytz = "^2023.2"
lxml = "^4.9.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
