[tool.poetry]
name = "testbed-image"
version = "0.1.0"
description = "FMI Testbed image fetcher"
authors = ["Tero Paloheimo <tero.paloheimo@iki.fi>"]
packages = [{include = "testbed_image.py"}]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.30.0"
beautifulsoup4 = "^4.12.0"
pytz = "^2024.0"
lxml = "^5.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
lint.select = ["B", "D", "E", "F", "G", "I", "N", "PERF", "PIE", "PL", "PTH", "SIM", "RUF", "S", "TRY", "W"]
lint.ignore = ["D203", "D213"]
target-version = "py312"
